{
 "title": "SPO_MQTT",
 "description": "Supports https://github.com/sapcc/mosquitto-exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# SPO Sistem\n\nDiagnostični podatki"
   }
  },
  {
   "title": "Čas delovanja",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "broker_uptime" }
   ]
  },
  {
   "title": "MQTT sporočila",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(broker_publish_messages_sent[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(broker_publish_messages_received[$__interval])*-1",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Povezanih klentov",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "broker_clients_connected" }
   ]
  },
  {
   "title": "Python",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(sending_counter_total[$__interval]))",
     "legendFormat": "Števec poslanih sporočil"
    }
   ]
  }
 ]
}